### ISSUE TITLE
Alex's Mobs dupe and Modded Boss capture

### ISSUE THREAD

**Issue by Harve** [Tfarcenim/Mob-Catcher#10]
Version: mobcatcher-1.16.4-3.2a.jar

Issue 1:
Right clicking a tamed tarantula hawk dupes the net.

Issue 2:
You can capture modded bosses

Please make this mod more configurable. Being able to set what mob can and can't spawn would go a long way.

**Comment by Tfarcenim** [comment]
Issue 1 is not something I am willing to look into at the moment as it's a crossmod issue and I have no freetime.

Issue 2 is resolved via adding boss mobs to the blacklisted tags.

> Please make this mod more configurable. Being able to set what mob can and can't spawn would go a long way.
 
This is already possible via tags

**Comment by Tfarcenim** [comment]
Yeah, not going to diagnose someone else's broken code, I have to port
