### ISSUE TITLE
Mob Capture Device dupe glitch

### ISSUE THREAD

**Issue by Nahkranoth0** [Tfarcenim/Mob-Catcher#2]
Issue: Mob Capture Device
When using the Mob Capture Device Launcher in Release mode to release a mob, it spawns the mob back and spawns two Mob Capture Device instead of just one.
This doesn't happen if used the Mob Capture Device by hand.

Steps to reproduce: Put Mob Capture Device Launcher in Release mode and release a previous captured mob

![2019-07-21_11 03 03](https://user-images.githubusercontent.com/11743887/61589796-2f1f9d80-aba7-11e9-894b-a7238ebf9ddf.png)

**Comment by Tfarcenim** [comment]
fixed in 1.2
