### ISSUE TITLE
I cannot capture tamed dogs by right clicking with a ball.

### ISSUE THREAD

**Issue by Barerock** [Tfarcenim/Mob-Catcher#5]
As the title says. I can do it with the launcher, just not a right click on the animal. Tested on 2 tamed wolves and 2 tamed cats; cats are working, but the dogs aren't.

Using 3.1 version for 1.16 and forge 35.1.10 on 1.16.4

**Comment by Tfarcenim** [comment]
Problem is the wolf has an empty right hand click interaction with them that activates before it reaches the code that handles held items.

As I do not wish to mess with this interaction, I'm closing this as a wontfix as there is a viable workaround.
