### ISSUE TITLE
Makes Client only call on the server side.

### ISSUE THREAD

**Issue by PongoSapiens** [Tfarcenim/Mob-Catcher#6]
ya, right here is the problem: https://github.com/Tfarcenim/Mob-Catcher/blob/1.14.x/src/main/java/com/tfar/mobcatcher/ItemNetLauncher.java#L143
I18n is not allowed server side
note that the import is import net.minecraft.client.resources.I18n;
getDisplayName() is allowed server side, so anything in the method should also be fine there
so this issue is on their end, just turns out that it is only noticed when thutcore asks for the display name of the item

**Comment by Tfarcenim** [comment]
Fixed in 3.2a
